"use client";
import { FormEvent, useEffect, useState } from "react";
type Student={id:number;university_id:string;full_name:string;email:string;role:string;status:string};
export default function AdminClient({adminName}:{adminName:string}){const[students,setStudents]=useState<Student[]>([]);const[msg,setMsg]=useState("");const[loading,setLoading]=useState(true);async function load(){setLoading(true);const r=await fetch("/api/students");setStudents(await r.json());setLoading(false)}useEffect(()=>{load()},[]);
async function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await save([{universityId:String(f.get("id")),fullName:String(f.get("name")),email:String(f.get("email")),role:String(f.get("role"))}]);e.currentTarget.reset()}
async function save(rows:unknown[]){const r=await fetch("/api/students",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({students:rows})});const d=await r.json();setMsg(r.ok?`تم حفظ ${d.count} سجل بنجاح`:d.error);if(r.ok)load()}
async function upload(file:File){const text=await file.text();const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);const rows=lines.slice(1).map(line=>{const c=line.split(",").map(x=>x.trim().replace(/^"|"$/g,""));return{universityId:c[0],fullName:c[1],email:c[2],role:c[3]||"student"}});await save(rows)}
async function toggle(s:Student){await fetch("/api/students",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:s.id,status:s.status==="active"?"disabled":"active"})});load()}
return <main className="admin-app" dir="rtl"><aside><div className="admin-brand">campus<b>Go</b></div><img src="/university-of-jordan.png" alt="الجامعة الأردنية"/><nav><button className="active">◉ إدارة الطلاب</button><button>▣ الباصات والخطوط</button><button>⌖ المحطات</button><button>▤ التقارير</button></nav><a href="/signout-with-chatgpt?return_to=/">تسجيل الخروج</a></aside><section className="admin-main"><header><div><span>لوحة التحكم</span><h1>مرحبًا، {adminName}</h1></div><div className="admin-badge">مدير النظام</div></header><div className="stats"><article><span>إجمالي الطلاب</span><b>{students.filter(s=>s.role==="student").length}</b></article><article><span>الحسابات النشطة</span><b>{students.filter(s=>s.status==="active").length}</b></article><article><span>الحسابات الموقوفة</span><b>{students.filter(s=>s.status==="disabled").length}</b></article></div><section className="manage"><div className="manage-head"><div><h2>إدارة حسابات الطلاب</h2><p>أضف طالبًا جديدًا أو ارفع قائمة بصيغة CSV</p></div><label className="upload">↑ رفع ملف CSV<input type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&upload(e.target.files[0])}/></label></div><form className="add-form" onSubmit={add}><input name="id" required placeholder="الرقم الجامعي"/><input name="name" required placeholder="الاسم الكامل"/><input name="email" required type="email" placeholder="البريد الإلكتروني"/><select name="role"><option value="student">طالب</option><option value="admin">أدمن</option></select><button>+ إضافة الحساب</button></form>{msg&&<div className="admin-msg">{msg}</div>}<div className="table-wrap"><table><thead><tr><th>الطالب</th><th>الرقم الجامعي</th><th>الصلاحية</th><th>الحالة</th><th>إجراء</th></tr></thead><tbody>{loading?<tr><td colSpan={5}>جاري التحميل...</td></tr>:students.map(s=><tr key={s.id}><td><b>{s.full_name}</b><small>{s.email}</small></td><td>{s.university_id}</td><td>{s.role==="admin"?"أدمن":"طالب"}</td><td><span className={s.status}>{s.status==="active"?"نشط":"موقوف"}</span></td><td>{s.role!=="admin"&&<button className="table-action" onClick={()=>toggle(s)}>{s.status==="active"?"إيقاف":"تفعيل"}</button>}</td></tr>)}</tbody></table></div></section><div className="csv-note">صيغة الملف: university_id, full_name, email, role</div></section></main>}
