import{FormEvent,useEffect,useState}from"react";
import{supabase,type Profile}from"./supabase";

type Tab="students"|"transport"|"stops";
type Route={id:number;name:string;origin:string;destination:string;color:string;active:boolean};
type Stop={id:number;route_id:number|null;name:string;landmark:string;stop_order:number};
type Bus={id:number;code:string;driver_name:string;capacity:number;route_id:number|null;status:string};
type Trip={id:number;bus_code:string;route_name:string;stop_name:string;departure_time:string;arrival_time:string;active:boolean};
type Lecture={id:number;student_id:number;course_name:string;building:string;room:string;day_of_week:number;start_time:string;end_time:string};
const days=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
const tm=(v:string)=>v?.slice(0,5);

export default function AdminDashboard({profile}:{profile:Profile}){
 const[tab,setTab]=useState<Tab>("students");const[users,setUsers]=useState<Profile[]>([]);const[routes,setRoutes]=useState<Route[]>([]);const[stops,setStops]=useState<Stop[]>([]);const[buses,setBuses]=useState<Bus[]>([]);const[trips,setTrips]=useState<Trip[]>([]);const[selected,setSelected]=useState<Profile|null>(null);const[lectures,setLectures]=useState<Lecture[]>([]);const[assigned,setAssigned]=useState<number|"">("");const[msg,setMsg]=useState("");
 async function load(){const[qUsers,qRoutes,qStops,qBuses,qTrips]=await Promise.all([supabase.from("user_directory").select("*").order("id",{ascending:false}),supabase.from("transport_routes").select("*").order("name"),supabase.from("bus_stops").select("*").order("stop_order"),supabase.from("buses").select("*").order("code"),supabase.from("bus_trips").select("*").order("departure_time")]);setUsers((qUsers.data||[])as Profile[]);setRoutes((qRoutes.data||[])as Route[]);setStops((qStops.data||[])as Stop[]);setBuses((qBuses.data||[])as Bus[]);setTrips((qTrips.data||[])as Trip[])}useEffect(()=>{load()},[]);
 const ok=(text:string)=>{setMsg(text);setTimeout(()=>setMsg(""),2800)};
 async function addRoute(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from("transport_routes").insert({name:f.get("name"),origin:f.get("origin"),destination:f.get("destination"),color:f.get("color")});if(error)return ok(error.message);e.currentTarget.reset();ok("تمت إضافة المسار");load()}
 async function addBus(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from("buses").insert({code:f.get("code"),driver_name:f.get("driver"),capacity:Number(f.get("capacity")),route_id:f.get("route")?Number(f.get("route")):null,status:"active"});if(error)return ok(error.message);e.currentTarget.reset();ok("تمت إضافة الباص");load()}
 async function addTrip(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const bus=buses.find(x=>x.id===Number(f.get("bus")));const route=routes.find(x=>x.id===bus?.route_id);const stop=stops.find(x=>x.id===Number(f.get("stop")));if(!bus)return ok("اختر باصًا");const{error}=await supabase.from("bus_trips").insert({bus_code:bus.code,route_name:route?.name||"بدون مسار",stop_name:stop?.name||"بدون محطة",departure_time:f.get("departure"),arrival_time:f.get("arrival")});if(error)return ok(error.message);e.currentTarget.reset();ok("تمت إضافة الموعد");load()}
 async function addStop(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const{error}=await supabase.from("bus_stops").insert({route_id:Number(f.get("route")),name:f.get("name"),landmark:f.get("landmark"),stop_order:Number(f.get("order"))});if(error)return ok(error.message);e.currentTarget.reset();ok("تمت إضافة المحطة");load()}
 async function del(table:string,id:number){if(!confirm("هل تريد الحذف؟"))return;const{error}=await supabase.from(table).delete().eq("id",id);if(error)return ok(error.message);ok("تم الحذف");load()}
 async function role(u:Profile,value:"student"|"admin"){await supabase.from("user_directory").update({role:value}).eq("id",u.id);ok("تم تحديث الصلاحية");load()}
 async function status(u:Profile){await supabase.from("user_directory").update({status:u.status==="active"?"disabled":"active"}).eq("id",u.id);load()}
 async function openStudent(u:Profile){setSelected(u);const[l,a]=await Promise.all([supabase.from("lectures").select("*").eq("student_id",u.id).order("day_of_week").order("start_time"),supabase.from("student_bus_assignments").select("trip_id").eq("student_id",u.id).maybeSingle()]);setLectures((l.data||[])as Lecture[]);setAssigned((a.data as{trip_id:number}|null)?.trip_id||"")}
 async function addLecture(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!selected)return;const f=new FormData(e.currentTarget);const{error}=await supabase.from("lectures").insert({student_id:selected.id,course_name:f.get("course"),building:f.get("building"),room:f.get("room"),day_of_week:Number(f.get("day")),start_time:f.get("start"),end_time:f.get("end")});if(error)return ok(error.message);e.currentTarget.reset();ok("تمت إضافة المحاضرة");openStudent(selected)}
 async function assign(value:string){if(!selected)return;setAssigned(value?Number(value):"");if(value)await supabase.from("student_bus_assignments").upsert({student_id:selected.id,trip_id:Number(value),updated_at:new Date().toISOString()});else await supabase.from("student_bus_assignments").delete().eq("student_id",selected.id);ok("تم تحديث رحلة الطالب")}
 return <main className="admin-app" dir="rtl"><aside><div className="admin-brand">campus<b>Go</b></div><img src="/university-of-jordan.png" alt="الجامعة الأردنية"/><nav><button className={tab==="students"?"active":""} onClick={()=>setTab("students")}>◉ إدارة الطلاب</button><button className={tab==="transport"?"active":""} onClick={()=>setTab("transport")}>▣ الباصات والخطوط</button><button className={tab==="stops"?"active":""} onClick={()=>setTab("stops")}>⌖ المحطات</button></nav><button className="aside-logout" onClick={()=>supabase.auth.signOut()}>تسجيل الخروج</button></aside><section className="admin-main"><header><div><span>لوحة التحكم</span><h1>{tab==="students"?"إدارة الطلاب والمحاضرات":tab==="transport"?"الباصات والخطوط والمواعيد":"إدارة المحطات"}</h1></div><div className="admin-badge">{profile.full_name}</div></header>{msg&&<div className="admin-msg">{msg}</div>}{tab==="students"&&<Students/>}{tab==="transport"&&<Transport/>}{tab==="stops"&&<Stops/>}</section></main>;

 function Students(){return <><div className="stats"><article><span>الحسابات</span><b>{users.length}</b></article><article><span>الطلاب</span><b>{users.filter(x=>x.role==="student").length}</b></article><article><span>الأدمن</span><b>{users.filter(x=>x.role==="admin").length}</b></article></div><section className="manage"><h2>حسابات الطلاب</h2><p>افتح ملف الطالب لإضافة محاضراته وتعيين رحلة الباص</p><div className="table-wrap"><table><thead><tr><th>الحساب</th><th>الرقم</th><th>الصلاحية</th><th>الحالة</th><th>الإجراء</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><b>{u.full_name}</b><small>{u.email}</small></td><td>{u.university_id}</td><td>{u.user_id===profile.user_id?<span className="role-owner">أدمن رئيسي</span>:<select className="role-select" value={u.role} onChange={e=>role(u,e.target.value as"student"|"admin")}><option value="student">طالب</option><option value="admin">أدمن</option></select>}</td><td><span className={u.status}>{u.status==="active"?"نشط":"موقوف"}</span></td><td><button className="profile-open" onClick={()=>openStudent(u)}>فتح الملف</button>{u.user_id!==profile.user_id&&<button className="table-action" onClick={()=>status(u)}>{u.status==="active"?"إيقاف":"تفعيل"}</button>}</td></tr>)}</tbody></table></div></section>{selected&&<section className="manage student-editor dashboard-editor"><div className="editor-title"><div><span>ملف الطالب</span><h2>{selected.full_name}</h2></div><button onClick={()=>setSelected(null)}>×</button></div><label className="field-label">رحلة الباص<select value={assigned} onChange={e=>assign(e.target.value)}><option value="">بدون رحلة</option>{trips.map(t=><option key={t.id} value={t.id}>{t.bus_code} — {t.route_name} ({tm(t.departure_time)})</option>)}</select></label><h3>إضافة محاضرة</h3><form className="lecture-form" onSubmit={addLecture}><input name="course" required placeholder="اسم المساق"/><input name="building" required placeholder="المبنى"/><input name="room" required placeholder="القاعة"/><select name="day">{days.map((d,i)=><option value={i} key={d}>{d}</option>)}</select><input name="start" type="time" required/><input name="end" type="time" required/><button>+ إضافة محاضرة</button></form><div className="lecture-list">{lectures.map(l=><div key={l.id}><span><b>{l.course_name}</b><small>{days[l.day_of_week]} · {tm(l.start_time)}–{tm(l.end_time)} · {l.building} {l.room}</small></span><button onClick={async()=>{await supabase.from("lectures").delete().eq("id",l.id);openStudent(selected)}}>حذف</button></div>)}</div></section>}</>}
 function Transport(){return <><div className="transport-grid"><section className="manage"><h2>إضافة مسار</h2><form className="data-form" onSubmit={addRoute}><input name="name" required placeholder="اسم المسار: بوابة الشمال"/><input name="origin" required placeholder="نقطة البداية"/><input name="destination" required placeholder="الوجهة"/><label>لون المسار<input name="color" type="color" defaultValue="#08714f"/></label><button>إضافة المسار</button></form><div className="entity-list">{routes.map(r=><div key={r.id}><i style={{background:r.color}}/><span><b>{r.name}</b><small>{r.origin} ← {r.destination}</small></span><button onClick={()=>del("transport_routes",r.id)}>حذف</button></div>)}</div></section><section className="manage"><h2>إضافة باص</h2><form className="data-form" onSubmit={addBus}><input name="code" required placeholder="رمز الباص U-12"/><input name="driver" placeholder="اسم السائق"/><input name="capacity" type="number" min="1" defaultValue="40"/><select name="route"><option value="">بدون مسار</option>{routes.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}</select><button>إضافة الباص</button></form><div className="entity-list">{buses.map(b=><div key={b.id}><span className="bus-symbol">🚌</span><span><b>{b.code}</b><small>{b.driver_name||"بدون سائق"} · {routes.find(r=>r.id===b.route_id)?.name||"بدون مسار"}</small></span><button onClick={()=>del("buses",b.id)}>حذف</button></div>)}</div></section></div><section className="manage trip-manager"><h2>مواعيد الرحلات</h2><form className="trip-form" onSubmit={addTrip}><select name="bus" required><option value="">اختر الباص</option>{buses.map(b=><option value={b.id} key={b.id}>{b.code}</option>)}</select><select name="stop"><option value="">اختر المحطة</option>{stops.map(s=><option value={s.id} key={s.id}>{s.name}</option>)}</select><label>الانطلاق<input name="departure" type="time" required/></label><label>الوصول<input name="arrival" type="time" required/></label><button>إضافة الموعد</button></form><div className="trip-list">{trips.map(t=><div key={t.id}><b>{t.bus_code}</b><span>{t.route_name} · {t.stop_name}</span><time>{tm(t.departure_time)} — {tm(t.arrival_time)}</time><button onClick={()=>del("bus_trips",t.id)}>حذف</button></div>)}</div></section></>}
 function Stops(){return <div className="transport-grid"><section className="manage"><h2>إضافة محطة</h2><form className="data-form" onSubmit={addStop}><select name="route" required><option value="">اختر المسار</option>{routes.map(r=><option value={r.id} key={r.id}>{r.name}</option>)}</select><input name="name" required placeholder="اسم المحطة"/><input name="landmark" placeholder="معلم قريب"/><input name="order" type="number" min="1" defaultValue="1"/><button>إضافة المحطة</button></form></section><section className="manage"><h2>المحطات المسجلة</h2><div className="entity-list stops-list">{stops.map(s=><div key={s.id}><span className="stop-number">{s.stop_order}</span><span><b>{s.name}</b><small>{routes.find(r=>r.id===s.route_id)?.name||"بدون مسار"} · {s.landmark}</small></span><button onClick={()=>del("bus_stops",s.id)}>حذف</button></div>)}</div></section></div>}
}
