import { useEffect, useState } from "react";
import { supabase, type Profile } from "./supabase";
type Lecture={id:number;course_name:string;building:string;room:string;day_of_week:number;start_time:string;end_time:string};
type Bus={id:number;code:string;driver_name:string;status:string;current_location:string;location_updated_at:string|null};
const days=["الأحد","الاثنين","الثلاثاء","الأربعاء","الخميس","الجمعة","السبت"];
const tm=(v:string)=>v?.slice(0,5);
export default function StudentDashboard({profile}:{profile:Profile}){
 const[lectures,setLectures]=useState<Lecture[]>([]);const[buses,setBuses]=useState<Bus[]>([]);const[loading,setLoading]=useState(true);
 async function load(){setLoading(true);const[l,b]=await Promise.all([supabase.from("lectures").select("*").eq("student_id",profile.id).order("day_of_week").order("start_time"),supabase.from("buses").select("id,code,driver_name,status,current_location,location_updated_at").neq("status","inactive").order("code")]);setLectures((l.data||[])as Lecture[]);setBuses((b.data||[])as Bus[]);setLoading(false)}
 useEffect(()=>{load()},[profile.id]);
 return <main className="student-app student-simple" dir="rtl"><header><div className="mini-brand">campus<b>Go</b></div><img src="/university-of-jordan.png" alt="الجامعة الأردنية"/><div className="student-actions"><span>طالب</span><button onClick={()=>supabase.auth.signOut()}>تسجيل الخروج</button></div></header><section className="student-body"><div className="student-welcome"><span>الجامعة الأردنية</span><h1>أهلًا، {profile.full_name} 👋</h1><small>محاضراتك وخريطة باصات الجامعة</small></div>{loading?<div className="student-loading">جاري تحميل بياناتك...</div>:<div className="student-simple-grid"><section className="campus-map-section"><div className="student-section-title"><div><span>داخل الحرم الجامعي</span><h2>خريطة الباصات</h2></div><button onClick={load}>تحديث المواقع</button></div><div className="uj-map"><iframe title="خريطة الجامعة الأردنية" loading="lazy" src="https://www.openstreetmap.org/export/embed.html?bbox=35.8585%2C32.0060%2C35.8815%2C32.0225&layer=mapnik&marker=32.0149%2C35.8707"/><div className="map-name">كلية الطب ← كلية العلوم التربوية</div></div><div className="map-buses">{buses.length?buses.map(b=><article key={b.id}><span className="bus-icon">🚌</span><div><b>{b.code}</b><strong>⌖ {b.current_location||"الموقع غير محدد"}</strong><small>{b.driver_name?`السائق: ${b.driver_name}`:""}{b.location_updated_at?` · آخر تحديث ${new Date(b.location_updated_at).toLocaleString("ar-JO")}`:""}</small></div><i className={b.status}/></article>):<p className="empty-state">لم تتم إضافة باصات بعد.</p>}</div></section><aside className="my-lectures"><div className="student-section-title"><div><span>خاص بحسابك فقط</span><h2>محاضراتي</h2></div></div><div className="student-data-list">{lectures.length?lectures.map(x=><div key={x.id}><time>{tm(x.start_time)}</time><span><b>{x.course_name}</b><small>{days[x.day_of_week]} · {x.building} · قاعة {x.room}</small></span></div>):<p className="empty-state">لم يضف مسؤول النظام محاضراتك بعد.</p>}</div></aside></div>}</section><footer>POWERED BY <b>LUMINODE</b></footer></main>
}
